---
- name: "Update apt cache"
  apt:
    name: "*"
    update_cache: yes

# Install packages that don't need reboot
- name: "install packages"
  apt:
    name:
      - "{{ item }}"
    state: latest
  loop: "{{ packages }}"

# Install VS code
- name: "Install VS code"
  block:
    - name: "Pull and install apt repository and signing key"
      shell: |
        sudo apt-get install wget gpg

        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor

        sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg

        sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'

        rm -f packages.microsoft.gpg
      args:
        executable: /bin/bash
    - name: "Update package cache and install vs code packages"
      shell: |
        sudo apt install apt-transport-https

        sudo apt update

        sudo apt install code
      args:
        executable: /bin/bash

- name: Install ubuntu-desktop
  apt:
    name: ubuntu-desktop
    state: present

- name: Reboot the system (optional)
  reboot: